### ISSUE TITLE
Simulation model

### ISSUE THREAD

**Issue by sashkinaaa** [martendo/gpss.py#2]
Hello,

I am trying to convert a simulation model that was made in GPSS World Student Version into a model that can be run with your GPSS simulator. 
The original model is attached (
[OriginalGPSS.txt](https://github.com/martendo/gpss.py/files/13772835/OriginalGPSS.txt)
)
and the one that I tried to create and run with your simulator is also atached (
[model.txt](https://github.com/martendo/gpss.py/files/13772852/model.txt)
)
The problem I have is that the simulation passes only once and stops. 
Can you please help me to run that model with your simulator?
Thank you in advance!

**Comment by martendo** [comment]
Oh, hi there!

Since you're saying that your simulation did run, I'm going to guess that you've made changes to gpss.py to allow for the non-integer values you're using in the `ADVANCE` Blocks? gpss.py in its current state would fail to parse those (which seems to be an unnecessary limitation, but that can be changed fairly easily).

As for your issue, I noticed that line 51 of model.txt differs from line 60 of OriginalGPSS.txt:
```diff
-TRANSFER ,BBB1
+TRANSFER 1,,BBB1
```

gpss.py will interpret the `1` as a value of parts-per-thousand (i.e. 0.001), meaning that the jump is extremely unlikely to occur, which is probably why it doesn't. (According to its manual, it looks like GPSS World would interpret this the same way.) I'm assuming you want an unconditional jump instead, so I'd recommend keeping the line from OriginalGPSS.txt unchanged &mdash; gpss.py supports the "Unconditional Mode" too!

I hope that helps.
gpss.py is very incomplete. I haven't worked on it for quite a while and I might not have the time for major changes any time soon, so I don't know how far you'll get with your simulations. In any case, good luck!

**Comment by sashkinaaa** [comment]
Hi, 

It is strange that I haven't made any changes to the gpss.py to allow non-integer values in the ADVANCE blocks, but I had to define the exponential function at the beginning and use it in the ADVANCE blocks, because otherwise it did not work at all.

When I try to use the TRANSFER as in the original GPSS, I get an error:
"gpss.error.SimulationError: model.gps(25): Cannot ADVANCE a negative amount of time (-1)" and that is why I tried it that way.
Maybe the error is due to the exponential function I use in the ADVANCE blocks.

Anyway, it is not such a big problem so I am closing the issue and wish you a happy new year.

Best regards, 
Aleksandar

**Comment by martendo** [comment]
Ah, gpss.py may have an incorrect implementation here: it treats the evaluated function in the B Operand of the `ADVANCE` Block as the time half-range, the same as if you supplied a number directly. This means the time increment will range from the A Operand value plus or minus the value from the B Operand function, which with your function can be negative.

I'd like to check some original GPSS manuals to determine what the original behaviour is, but here gpss.py is indeed inconsistent with GPSS World. This is something I may look to fix sometime.
